###

GET http://localhost:4000 



###

GET http://localhost:4000/Posts






###
POST http://localhost:4000/Posts
Content-Type: application/json

{
    "author": "moshe",
    "title":"pizze",
    "content":"no contnt"
}
###


GET http://localhost:4000/Posts/6738e28726f0618758d20437

###
GET http://localhost:4000/Posts?author=YOSSI


###

PUT http://localhost:4000/Posts/6738e6e8237f69137a275ea1
Content-Type: application/json

{
    "_id" : "6738e6e8237f69137a275ea1",
    "content": "new post "

}

###
POST http://localhost:4000/Comments
Content-Type: application/json

{
    "comment_user":"pizza",
    "title":"i like pizza too",
    "comment_content" : " pizza is the best forever",
    "post_id": "6739c578bdeff3469703430f" 
}

### 
GET http://localhost:4000/Comments


###
GET http://localhost:4000/Comments?post_id=673f79c613d76d7ce47b7723

###
PUT http://localhost:4000/Comments/673f7cba7e1d713764475d45 
Content-Type: application/json

{
    "_id" : "673f7cba7e1d713764475d45",
    "content": " new content everywhere here "
}
### 
DELETE http://localhost:4000/Comments/delete/6739c578bdeff3469703430f

