###

GET http://localhost:4000   
// HOME PAGE




###

GET http://localhost:4000/Posts

// GET ALL POSTS






###
POST http://localhost:4000/Posts
Content-Type: application/json

{
    "author": "Rotemfdfdsf",
    "title":"TEST2",
    "content":"FSDFSDFSDFDS"
}

// ADD NEW POST 
###


GET http://localhost:4000/Posts/67434205de06d55a7000db8f

// GET POST BY ID

###
GET http://localhost:4000/Posts?author=Rotem

// GET POST BY AUTHOR WHICH IS Rotem IN THIS CASE

###

PUT http://localhost:4000/Posts/67434205de06d55a7000db8f
Content-Type: application/json

{
    "_id" : "673a0285731c0b261039fae7",
    "content": "CONTENT UPDATED TEST "

}

// UPDATE POST BY ID

###
POST http://localhost:4000/Comments
Content-Type: application/json

{
    "comment_user":"Shodfsfdfsn",
    "title":"pizza is the best", 
    "comment_content" : " I love pizza so much ", 
    "post_id": "6739c578bdeff3469703430f" 
}

// ADD NEW COMMENT TO POST BY ID
### 
GET http://localhost:4000/Comments

// GET ALL COMMENTS ON DB


###
GET http://localhost:4000/Comments?post_id=6757405bfa284f94e94d830f

// GET ALL COMMENTS BY  A SPECIFIEC POST ID

###
PUT http://localhost:4000/Comments/675746aed700a5f0893f9a71
Content-Type: application/json

{
    "_id" : "673f7cba7e1d713764475d45",
    "comment_content": " new comment update for test "
}
// UPDATE COMMENT BY ID


###

DELETE http://localhost:4000/Comments/6743425ede06d55a7000db9b

// DELETE COMMENT BY ID


