###

GET http://localhost:4000 



###

GET http://localhost:4000/Posts






###

POST http://localhost:4000/Posts
Content-Type: application/json

{
    "author": "YOSSI",
    "title":"MY FIRST POST",
    "content":"I LIKE TO WRITE and just made new"


    
   
}
###


GET http://localhost:4000/Posts/6738e28726f0618758d20437

###
GET http://localhost:4000/Posts?author=YOSSI


###

PUT http://localhost:4000/Posts/6738e6e8237f69137a275ea1
Content-Type: application/json

{
    "_id" : "6738e6e8237f69137a275ea1",
    "content": "PUT REQUEST ENDED + "

}

